export { MediaController } from './media.controller.js'
export { GenresController } from './genres.controller.js'
export { PlatformsController } from './platforms.controller.js'
export { UsersController } from './users.controller.js'
export { ArticlesController } from './articles.controller.js'
export { CuratedListsController } from './curated-lists.controller.js'

export { MovieController } from './tmdb/movie.controller.js'
export { PersonController } from './tmdb/person.controller.js'
export { CreditsController } from './tmdb/credits.controller.js'
